# サーバー起動60秒後にwhitelistをどうするか
whitelist-after60sec:
  status: false

# luckpermsでgroup.gm持ってないopを確認するかどうか
opcheck-byluckperms:
  status: false

# 初ログインユーザーへの初心者キット配布設定
# @man10のみ status: true 想定
newbiekit-give:
  status: false
  # 配るキットのデータ
  inv: