name: Man10Essentials
version: '1.0-SNAPSHOT'
main: io.github.uttmangosteen.man10Essentials.Main
api-version: '1.20'
softdepend:
  - HuskSync

commands:
  ec:
    permission: red.man10.ec
  mhat:
    permission: red.man10.mhat
  ohatsukit:
    usage: "
    §d/ohatsukit <on|off> ...onじゃない鯖に最初に入るとkitが貰えない\n
    §d/ohatsukit register ...自分の装備と所持品がohatsukitになる\n
    §d/ohatsukit give [mcid] ...ohatsukitをplayerにgiveする(溢れた分は消える)\n"
    permission: red.man10.ohatsukit
permissions:
  red.man10.ec:
    default: op
  red.man10.mhat:
    default: op
  red.man10.ohatsukit:
    default: op