name: Man10Essentials
version: '1.0-SNAPSHOT'
main: io.github.uttmangosteen.man10Essentials.Main
api-version: '1.20'

commands:
  ec:
    permission: red.man10.ec
  ohatsukit:
    usage: "/ohatsukit <on|off> ...man10でだけonを打つ想定\n
            /ohatsukit register ...自分の装備と所持品がohatsukitになる\n
            /ohatsukit give [mcid] ...ohatsukitをplayerにgiveする(溢れたら消える)\n"
    permission: red.man10.ohatsukit
permissions:
  red.man10.ec:
    default: op
  red.man10.ohatsukit:
    default: op