name: Man10Essentials
version: '1.0-SNAPSHOT'
main: io.github.uttmangosteen.man10Essentials.Main
api-version: '1.20'

commands:
  ec:
    permission: red.man10.ec
  ohatsukit:
    usage: "/ohatsukit <on|off>\n
            man10kitのコマンド/kit set [mcid] newbie 発行してるだけ
            man10でだけonにする想定でいます"
    permission: red.man10.ohatsukit
permissions:
  red.man10.ec:
    default: op
  red.man10.ohatsukit:
    default: op